### YamlMime:ManagedReference
items:
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  commentId: T:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  id: Constants.EnvironmentVariables
  parent: DocFxToTemplate.Models.DocFx
  children:
  - DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_KEEP_DEBUG_INFO
  - DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  - DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_SOURCE_BRANCH_NAME
  - DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo
  - DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList
  - DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName
  langs:
  - csharp
  - vb
  name: Constants.EnvironmentVariables
  nameWithType: Constants.EnvironmentVariables
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  type: Class
  source:
    id: EnvironmentVariables
    path: T:\Projekty\DocFxToTemplate\src\DocFxToTemplate\Models\DocFx\Constants.cs
    startLine: 114
  assemblies:
  - DocFxToTemplate
  namespace: DocFxToTemplate.Models.DocFx
  syntax:
    content: public static class Constants.EnvironmentVariables
    content.vb: Public Module Constants.EnvironmentVariables
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_KEEP_DEBUG_INFO
  commentId: F:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_KEEP_DEBUG_INFO
  id: DOCFX_KEEP_DEBUG_INFO
  parent: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  langs:
  - csharp
  - vb
  name: DOCFX_KEEP_DEBUG_INFO
  nameWithType: Constants.EnvironmentVariables.DOCFX_KEEP_DEBUG_INFO
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_KEEP_DEBUG_INFO
  type: Field
  source:
    id: DOCFX_KEEP_DEBUG_INFO
    path: T:\Projekty\DocFxToTemplate\src\DocFxToTemplate\Models\DocFx\Constants.cs
    startLine: 130
  assemblies:
  - DocFxToTemplate
  namespace: DocFxToTemplate.Models.DocFx
  syntax:
    content: public const string DOCFX_KEEP_DEBUG_INFO = "DOCFX_KEEP_DEBUG_INFO"
    return:
      type: System.String
    content.vb: Public Const DOCFX_KEEP_DEBUG_INFO As String = "DOCFX_KEEP_DEBUG_INFO"
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  commentId: F:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  id: DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  parent: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  langs:
  - csharp
  - vb
  name: DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  nameWithType: Constants.EnvironmentVariables.DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
  type: Field
  source:
    id: DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST
    path: T:\Projekty\DocFxToTemplate\src\DocFxToTemplate\Models\DocFx\Constants.cs
    startLine: 132
  assemblies:
  - DocFxToTemplate
  namespace: DocFxToTemplate.Models.DocFx
  syntax:
    content: public const string DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST = "DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST"
    return:
      type: System.String
    content.vb: Public Const DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST As String = "DOCFX_NO_CHECK_CERTIFICATE_REVOCATION_LIST"
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_SOURCE_BRANCH_NAME
  commentId: F:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_SOURCE_BRANCH_NAME
  id: DOCFX_SOURCE_BRANCH_NAME
  parent: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  langs:
  - csharp
  - vb
  name: DOCFX_SOURCE_BRANCH_NAME
  nameWithType: Constants.EnvironmentVariables.DOCFX_SOURCE_BRANCH_NAME
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.DOCFX_SOURCE_BRANCH_NAME
  type: Field
  source:
    id: DOCFX_SOURCE_BRANCH_NAME
    path: T:\Projekty\DocFxToTemplate\src\DocFxToTemplate\Models\DocFx\Constants.cs
    startLine: 135
  assemblies:
  - DocFxToTemplate
  namespace: DocFxToTemplate.Models.DocFx
  syntax:
    content: public const string DOCFX_SOURCE_BRANCH_NAME = "DOCFX_SOURCE_BRANCH_NAME"
    return:
      type: System.String
    content.vb: Public Const DOCFX_SOURCE_BRANCH_NAME As String = "DOCFX_SOURCE_BRANCH_NAME"
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo
  commentId: P:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo
  id: KeepDebugInfo
  parent: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  langs:
  - csharp
  - vb
  name: KeepDebugInfo
  nameWithType: Constants.EnvironmentVariables.KeepDebugInfo
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo
  type: Property
  source:
    id: KeepDebugInfo
    path: T:\Projekty\DocFxToTemplate\src\DocFxToTemplate\Models\DocFx\Constants.cs
    startLine: 139
  assemblies:
  - DocFxToTemplate
  namespace: DocFxToTemplate.Models.DocFx
  syntax:
    content: public static string? KeepDebugInfo { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property KeepDebugInfo As String
  overload: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo*
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList
  commentId: P:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList
  id: NoCheckCertificateRevocationList
  parent: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  langs:
  - csharp
  - vb
  name: NoCheckCertificateRevocationList
  nameWithType: Constants.EnvironmentVariables.NoCheckCertificateRevocationList
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList
  type: Property
  source:
    id: NoCheckCertificateRevocationList
    path: T:\Projekty\DocFxToTemplate\src\DocFxToTemplate\Models\DocFx\Constants.cs
    startLine: 141
  assemblies:
  - DocFxToTemplate
  namespace: DocFxToTemplate.Models.DocFx
  syntax:
    content: public static bool NoCheckCertificateRevocationList { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared ReadOnly Property NoCheckCertificateRevocationList As Boolean
  overload: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList*
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName
  commentId: P:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName
  id: SourceBranchName
  parent: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables
  langs:
  - csharp
  - vb
  name: SourceBranchName
  nameWithType: Constants.EnvironmentVariables.SourceBranchName
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName
  type: Property
  source:
    id: SourceBranchName
    path: T:\Projekty\DocFxToTemplate\src\DocFxToTemplate\Models\DocFx\Constants.cs
    startLine: 144
  assemblies:
  - DocFxToTemplate
  namespace: DocFxToTemplate.Models.DocFx
  syntax:
    content: public static string? SourceBranchName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property SourceBranchName As String
  overload: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName*
references:
- uid: DocFxToTemplate.Models.DocFx
  commentId: N:DocFxToTemplate.Models.DocFx
  href: DocFxToTemplate.html
  name: DocFxToTemplate.Models.DocFx
  nameWithType: DocFxToTemplate.Models.DocFx
  fullName: DocFxToTemplate.Models.DocFx
  spec.csharp:
  - uid: DocFxToTemplate
    name: DocFxToTemplate
    href: DocFxToTemplate.html
  - name: .
  - uid: DocFxToTemplate.Models
    name: Models
    href: DocFxToTemplate.Models.html
  - name: .
  - uid: DocFxToTemplate.Models.DocFx
    name: DocFx
    href: DocFxToTemplate.Models.DocFx.html
  spec.vb:
  - uid: DocFxToTemplate
    name: DocFxToTemplate
    href: DocFxToTemplate.html
  - name: .
  - uid: DocFxToTemplate.Models
    name: Models
    href: DocFxToTemplate.Models.html
  - name: .
  - uid: DocFxToTemplate.Models.DocFx
    name: DocFx
    href: DocFxToTemplate.Models.DocFx.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo*
  commentId: Overload:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo
  href: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.html#DocFxToTemplate_Models_DocFx_Constants_EnvironmentVariables_KeepDebugInfo
  name: KeepDebugInfo
  nameWithType: Constants.EnvironmentVariables.KeepDebugInfo
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.KeepDebugInfo
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList*
  commentId: Overload:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList
  href: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.html#DocFxToTemplate_Models_DocFx_Constants_EnvironmentVariables_NoCheckCertificateRevocationList
  name: NoCheckCertificateRevocationList
  nameWithType: Constants.EnvironmentVariables.NoCheckCertificateRevocationList
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.NoCheckCertificateRevocationList
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName*
  commentId: Overload:DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName
  href: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.html#DocFxToTemplate_Models_DocFx_Constants_EnvironmentVariables_SourceBranchName
  name: SourceBranchName
  nameWithType: Constants.EnvironmentVariables.SourceBranchName
  fullName: DocFxToTemplate.Models.DocFx.Constants.EnvironmentVariables.SourceBranchName
