name: release

on:
  release:
    types: [published, edited]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: restore
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore
      - name: test
        run: dotnet test --no-restore
      - name: pack
        run: |
            dotnet pack ./src/DocFxToTemplate/DocFxToTemplate.csproj --configuration Release -o ./dist/nupkg -p:Version=${VERSION}
            dotnet pack ./src/DocFxToTemplate.Tool/DocFxToTemplate.Tool.csproj --configuration Release -o ./dist/nupkg -p:Version=${VERSION}
      - name: push
        run: dotnet nuget push ./dist/nupkg/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
      - name: archive NuGet packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./dist/nupkg